### PR TITLE
Problem: Only main is considered for systemd

### PR DESCRIPTION
**Pull request by aquette**
Solution: Regenerate files with the latest zproject

Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>

### CODE REVIEW

**Comment by aquette** [comment]
Travis failure seems unrelated with the PR content:
...
ERROR: files left in build directory after distclean:

./stderr.txt
...

Content of stderr.txt:
[ERROR]: ../src/actor_commands.cc:90 (actor_commands) Expected multipart string format: PRODUCER/stream. Received PRODUCER/nullptr

**Comment by jimklimov** [comment]
Well, the issue is dual-natured: distcheck fails because the builddir is not wiped from temporary files (bad CLEANFILES setup in Makemodules-local.am); however in *this* case the stderr.txt file contains a failure trace of the test that probably should have been an assertion and should have failed when encountered (can't say more certainly without digging into code).

Maybe someone changed the protocols, but not everywhere yet...

**Comment by aquette** [comment]
@jimklimov same conclusion on my side as for the protocol change, but don't have more clues on who/why/where/when...

**Comment by geraldguillaume** [comment]
This looks like an old issue, actor_commands_test[actor_commands.cc] creates that file and doesn't clean it.
I recommend to drop it before leaving actor_commands_test procedure.

**Comment by geraldguillaume** [comment]
So we can merge it and fix it after

**Comment by jimklimov** [comment]
well... the https://github.com/42ity/fty-metric-store/blob/master/src/Makemodule-local.am is still in place and unchanged for a month... maybe the change is indeed with `sinclude` somehow

I wonder if it (`src/Makemodule-local.am`) must be explicitly `EXTRA_DIST`ed (if present, which would sort of defeat the purpose of zproject PR 860.... unless done via disk-hook...)?

**Comment by geraldguillaume** [comment]
see https://github.com/42ity/fty-metric-store/pull/13

**Pull request merged**
